// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: go/taskhub/callback/v1/callback.proto

package callbackv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskCallback_Dispatch_FullMethodName = "/taskhub.callback.v1.TaskCallback/Dispatch"
)

// TaskCallbackClient is the client API for TaskCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskCallback is the contract owner services implement for hub gRPC dispatch.
type TaskCallbackClient interface {
	// Dispatch accepts work for asynchronous execution. The RPC must return
	// quickly (Accepted); do not hold the call until the heavy job finishes.
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
}

type taskCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskCallbackClient(cc grpc.ClientConnInterface) TaskCallbackClient {
	return &taskCallbackClient{cc}
}

func (c *taskCallbackClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, TaskCallback_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskCallbackServer is the server API for TaskCallback service.
// All implementations must embed UnimplementedTaskCallbackServer
// for forward compatibility.
//
// TaskCallback is the contract owner services implement for hub gRPC dispatch.
type TaskCallbackServer interface {
	// Dispatch accepts work for asynchronous execution. The RPC must return
	// quickly (Accepted); do not hold the call until the heavy job finishes.
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	mustEmbedUnimplementedTaskCallbackServer()
}

// UnimplementedTaskCallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskCallbackServer struct{}

func (UnimplementedTaskCallbackServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedTaskCallbackServer) mustEmbedUnimplementedTaskCallbackServer() {}
func (UnimplementedTaskCallbackServer) testEmbeddedByValue()                      {}

// UnsafeTaskCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskCallbackServer will
// result in compilation errors.
type UnsafeTaskCallbackServer interface {
	mustEmbedUnimplementedTaskCallbackServer()
}

func RegisterTaskCallbackServer(s grpc.ServiceRegistrar, srv TaskCallbackServer) {
	// If the following call panics, it indicates UnimplementedTaskCallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskCallback_ServiceDesc, srv)
}

func _TaskCallback_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskCallbackServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskCallback_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskCallbackServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskCallback_ServiceDesc is the grpc.ServiceDesc for TaskCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskhub.callback.v1.TaskCallback",
	HandlerType: (*TaskCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _TaskCallback_Dispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go/taskhub/callback/v1/callback.proto",
}
