// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: go/taskhub/callback/v1/callback.proto

package callbackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchStatus int32

const (
	DispatchStatus_DISPATCH_STATUS_UNSPECIFIED DispatchStatus = 0
	DispatchStatus_DISPATCH_STATUS_ACCEPTED    DispatchStatus = 1
	DispatchStatus_DISPATCH_STATUS_REJECTED    DispatchStatus = 2
)

// Enum value maps for DispatchStatus.
var (
	DispatchStatus_name = map[int32]string{
		0: "DISPATCH_STATUS_UNSPECIFIED",
		1: "DISPATCH_STATUS_ACCEPTED",
		2: "DISPATCH_STATUS_REJECTED",
	}
	DispatchStatus_value = map[string]int32{
		"DISPATCH_STATUS_UNSPECIFIED": 0,
		"DISPATCH_STATUS_ACCEPTED":    1,
		"DISPATCH_STATUS_REJECTED":    2,
	}
)

func (x DispatchStatus) Enum() *DispatchStatus {
	p := new(DispatchStatus)
	*p = x
	return p
}

func (x DispatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_go_taskhub_callback_v1_callback_proto_enumTypes[0].Descriptor()
}

func (DispatchStatus) Type() protoreflect.EnumType {
	return &file_go_taskhub_callback_v1_callback_proto_enumTypes[0]
}

func (x DispatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchStatus.Descriptor instead.
func (DispatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_go_taskhub_callback_v1_callback_proto_rawDescGZIP(), []int{0}
}

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OwnerService  string                 `protobuf:"bytes,6,opt,name=owner_service,json=ownerService,proto3" json:"owner_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_go_taskhub_callback_v1_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_taskhub_callback_v1_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_go_taskhub_callback_v1_callback_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DispatchRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *DispatchRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *DispatchRequest) GetOwnerService() string {
	if x != nil {
		return x.OwnerService
	}
	return ""
}

type DispatchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  DispatchStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=taskhub.callback.v1.DispatchStatus" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// When status is REJECTED, retryable=false maps to a permanent archive.
	Retryable     bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_go_taskhub_callback_v1_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_taskhub_callback_v1_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_go_taskhub_callback_v1_callback_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetStatus() DispatchStatus {
	if x != nil {
		return x.Status
	}
	return DispatchStatus_DISPATCH_STATUS_UNSPECIFIED
}

func (x *DispatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DispatchResponse) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_go_taskhub_callback_v1_callback_proto protoreflect.FileDescriptor

const file_go_taskhub_callback_v1_callback_proto_rawDesc = "" +
	"\n" +
	"%go/taskhub/callback/v1/callback.proto\x12\x13taskhub.callback.v1\"\xba\x01\n" +
	"\x0fDispatchRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12#\n" +
	"\rowner_service\x18\x06 \x01(\tR\fownerService\"\x87\x01\n" +
	"\x10DispatchResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.taskhub.callback.v1.DispatchStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*m\n" +
	"\x0eDispatchStatus\x12\x1f\n" +
	"\x1bDISPATCH_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DISPATCH_STATUS_ACCEPTED\x10\x01\x12\x1c\n" +
	"\x18DISPATCH_STATUS_REJECTED\x10\x022g\n" +
	"\fTaskCallback\x12W\n" +
	"\bDispatch\x12$.taskhub.callback.v1.DispatchRequest\x1a%.taskhub.callback.v1.DispatchResponseB>Z<github.com/hinha/auth-sdks/go/taskhub/callback/v1;callbackv1b\x06proto3"

var (
	file_go_taskhub_callback_v1_callback_proto_rawDescOnce sync.Once
	file_go_taskhub_callback_v1_callback_proto_rawDescData []byte
)

func file_go_taskhub_callback_v1_callback_proto_rawDescGZIP() []byte {
	file_go_taskhub_callback_v1_callback_proto_rawDescOnce.Do(func() {
		file_go_taskhub_callback_v1_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_taskhub_callback_v1_callback_proto_rawDesc), len(file_go_taskhub_callback_v1_callback_proto_rawDesc)))
	})
	return file_go_taskhub_callback_v1_callback_proto_rawDescData
}

var file_go_taskhub_callback_v1_callback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_taskhub_callback_v1_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_taskhub_callback_v1_callback_proto_goTypes = []any{
	(DispatchStatus)(0),      // 0: taskhub.callback.v1.DispatchStatus
	(*DispatchRequest)(nil),  // 1: taskhub.callback.v1.DispatchRequest
	(*DispatchResponse)(nil), // 2: taskhub.callback.v1.DispatchResponse
}
var file_go_taskhub_callback_v1_callback_proto_depIdxs = []int32{
	0, // 0: taskhub.callback.v1.DispatchResponse.status:type_name -> taskhub.callback.v1.DispatchStatus
	1, // 1: taskhub.callback.v1.TaskCallback.Dispatch:input_type -> taskhub.callback.v1.DispatchRequest
	2, // 2: taskhub.callback.v1.TaskCallback.Dispatch:output_type -> taskhub.callback.v1.DispatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_go_taskhub_callback_v1_callback_proto_init() }
func file_go_taskhub_callback_v1_callback_proto_init() {
	if File_go_taskhub_callback_v1_callback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_taskhub_callback_v1_callback_proto_rawDesc), len(file_go_taskhub_callback_v1_callback_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_taskhub_callback_v1_callback_proto_goTypes,
		DependencyIndexes: file_go_taskhub_callback_v1_callback_proto_depIdxs,
		EnumInfos:         file_go_taskhub_callback_v1_callback_proto_enumTypes,
		MessageInfos:      file_go_taskhub_callback_v1_callback_proto_msgTypes,
	}.Build()
	File_go_taskhub_callback_v1_callback_proto = out.File
	file_go_taskhub_callback_v1_callback_proto_goTypes = nil
	file_go_taskhub_callback_v1_callback_proto_depIdxs = nil
}
